### ISSUE TITLE
Mobile Friendly

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc#20]
WFRC said that this isn't a high priority but worth taking a look at. Sounds like you can't see all of the tabs on smaller devices.

**Comment by nathankota** [comment]
First three tabs show up when map loads on mobile:
![Screenshot_20190917-081907](https://user-images.githubusercontent.com/15659642/65050231-4b7c5400-d924-11e9-8dc2-5c0932f812ee.png)

Last two tabs appear when the information panel is opened:
![Screenshot_20190917-081917](https://user-images.githubusercontent.com/15659642/65050284-618a1480-d924-11e9-8cb2-aa6ed7975f0e.png)

**Comment by stdavis** [comment]
b421f23cb057164ed42376c2ee070815db6a7406 takes care of the tabs but there are a few other issues:
- [ ] the sidebar should default to being closed on smaller devices
- [ ] the filter box is overlapped by the sherlock widget

**Comment by msilski** [comment]
The mobile-friendly logo looks good and having the Project Info window and Filter window hidden by default for smaller devices is a good idea. I think this is ready to go.

One note: for small screen sizes (ex. 340 x 650), once the left-side panel is expanded, it can't be closed because the blue button to expand/contract the panel is out of view. This could be a somewhat obscure use case (only my phone?), so I'm not 100% sure it's worth fixing. Perhaps the blue expand/contract button could be moved to inside the left-side panel for mobile? Not sure.

**Comment by stdavis** [comment]
> One note: for small screen sizes (ex. 340 x 650), once the left-side panel is expanded, it can't be closed because the blue button to expand/contract the panel is out of view. This could be a somewhat obscure use case (only my phone?), so I'm not 100% sure it's worth fixing. Perhaps the blue expand/contract button could be moved to inside the left-side panel for mobile? Not sure.

https://github.com/agrc/wfrc/issues/37

Thanks!
