### ISSUE TITLE
Land use tab: make parents into radio buttons

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc#31]
Jobs & Household should not be on at the same time as Land Use. Keep Land Use children as checkboxes.

**Comment by stdavis** [comment]
I spent about six hours on this the other day and wasn't able to implement it. I made some assumptions when I build the filter controls that make it so a significant rewrite would be required to implement this. My guess is another 10 or so hours. Would you like me to spend that time?

**Comment by nathankota** [comment]
FYI - there were 55.5 hours remaining as of yesterday, which does not include Scott's time towards the project yesterday and today.

**Comment by msilski** [comment]
In connection with issue #36, Bert and I wanted to offer another solution to clean up the Land Use tab while reducing the widget width. Instead of making all the layers radio buttons, we would like to split the group of four radio buttons into two groups of two radio buttons, as shown below:

![Revised Land Use Filter](https://user-images.githubusercontent.com/1699870/67440127-7d34aa80-f5b5-11e9-85de-aeb4784dafa4.png)

This would replace the original request in this item. Would this revised legend layout be any easier for you to implement?

**Comment by stdavis** [comment]
Yes! I think that this can be done via config updates alone. I closed #36 for now. We can open a new issue in the future if you want the width reduced.

**Comment by stdavis** [comment]
After config file update and reducing the widget width to `330px`...
![image](https://user-images.githubusercontent.com/1326248/67506021-8e2efb80-f649-11e9-856e-a2cbeee36ed5.png)

**Comment by msilski** [comment]
Wow! The new layout looks great.
