### ISSUE TITLE
Vision page info to HTML

### ISSUE THREAD

**Issue by nathankota** [agrc/wfrc#69]
**Summary:**
Utilize images and fonts found [here](https://drive.google.com/drive/u/0/folders/1zwEmc9pz5FDueEOZBNiBQgEVG-jR1V5_) to re-create the [Vision page's](https://wfrc.org/wasatch-choice-map/#mapList=vision.transportation.landuse.econdev.recreation.ato&selectedMap=vision&sideBarClosed=false) informational panel as images and html (and css?) to match closely the existing style and layout.  
> On our Vision tab we've got a number of pngs for the vision text. We need to convert these to formatted html text...

> We are not going for a perfect match (for example, QR codes and weird 4 square bullets under partners can be dropped) but want it to stay true to overall look and feel.

**Outcome:**
HTML, image files and perhaps some css within the Vision tab's About config.

**Comment by stdavis** [comment]
@steveoh I believe that I have the tooling set up to work on this issue. You should be able to check out the `html` branch, `npm start` and then open `http://localhost:3000/about-tests`. Our job is to create HTML in `vision-new.html` that replicates the content in the "vision" column.
![image](https://user-images.githubusercontent.com/1326248/95770197-48ae7880-0c76-11eb-8408-c161c7fff369.png)

For the other tabs, they have base-encoded all of the images within the HTML. However, I don't think that we necessarily need to. We could put the images in something like `public/about/images` and then reference them in our HTML.

For CSS, I'm thinking the best thing to do is to embed it within the HTML. Maybe we could create CSS classes within a `<style>` tag at the top of the file. We'd just need to make sure that it doesn't collide with other classes in the app.

And yes, I do see how tailwind may have been helpful in this circumstance. I've committed to start my next project with it. :)

Since all of the work for this issue will be contained in a single file `vision-new.html`, I'm not 100% sure how to coordinate our work on it. Maybe I'll start from the top and you work from the bottom? Maybe it would be better to come up with some sort of conventions before we both start working on it? I'll start working from the top and see how it goes.
